//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// Este código fuente fue generado automáticamente por wsdl, Versión=4.8.3928.0.
// 

namespace Mane.BD.WebServiceBd
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "ApiWebServiceSoap", Namespace = "http://tempuri.org/")]
    public partial class ApiWebService : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private WebApiUser usuarioValueField;

        private System.Threading.SendOrPostCallback ExecuteQueryOperationCompleted;

        private System.Threading.SendOrPostCallback ExecuteNonQueryOperationCompleted;

        private System.Threading.SendOrPostCallback ExecuteEscalarOperationCompleted;

        private System.Threading.SendOrPostCallback TestConnectionOperationCompleted;

        /// <remarks/>
        public ApiWebService()
        {
            this.Url = "https://localhost:44380/ManeBdWebService.asmx";
        }

        public WebApiUser UsuarioValue
        {
            get
            {
                return this.usuarioValueField;
            }
            set
            {
                this.usuarioValueField = value;
            }
        }

        /// <remarks/>
        public event ExecuteQueryCompletedEventHandler ExecuteQueryCompleted;

        /// <remarks/>
        public event ExecuteNonQueryCompletedEventHandler ExecuteNonQueryCompleted;

        /// <remarks/>
        public event ExecuteEscalarCompletedEventHandler ExecuteEscalarCompleted;

        /// <remarks/>
        public event TestConnectionCompletedEventHandler TestConnectionCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("UsuarioValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ExecuteQuery", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public WebApiResponse ExecuteQuery(string Query, string ConnName)
        {
            object[] results = this.Invoke("ExecuteQuery", new object[] {
                    Query,
                    ConnName});
            return ((WebApiResponse)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginExecuteQuery(string Query, string ConnName, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("ExecuteQuery", new object[] {
                    Query,
                    ConnName}, callback, asyncState);
        }

        /// <remarks/>
        public WebApiResponse EndExecuteQuery(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((WebApiResponse)(results[0]));
        }

        /// <remarks/>
        public void ExecuteQueryAsync(string Query, string ConnName)
        {
            this.ExecuteQueryAsync(Query, ConnName, null);
        }

        /// <remarks/>
        public void ExecuteQueryAsync(string Query, string ConnName, object userState)
        {
            if ((this.ExecuteQueryOperationCompleted == null))
            {
                this.ExecuteQueryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExecuteQueryOperationCompleted);
            }
            this.InvokeAsync("ExecuteQuery", new object[] {
                    Query,
                    ConnName}, this.ExecuteQueryOperationCompleted, userState);
        }

        private void OnExecuteQueryOperationCompleted(object arg)
        {
            if ((this.ExecuteQueryCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ExecuteQueryCompleted(this, new ExecuteQueryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("UsuarioValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ExecuteNonQuery", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public WebApiResponse ExecuteNonQuery(string Query, string ConnName)
        {
            object[] results = this.Invoke("ExecuteNonQuery", new object[] {
                    Query,
                    ConnName});
            return ((WebApiResponse)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginExecuteNonQuery(string Query, string ConnName, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("ExecuteNonQuery", new object[] {
                    Query,
                    ConnName}, callback, asyncState);
        }

        /// <remarks/>
        public WebApiResponse EndExecuteNonQuery(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((WebApiResponse)(results[0]));
        }

        /// <remarks/>
        public void ExecuteNonQueryAsync(string Query, string ConnName)
        {
            this.ExecuteNonQueryAsync(Query, ConnName, null);
        }

        /// <remarks/>
        public void ExecuteNonQueryAsync(string Query, string ConnName, object userState)
        {
            if ((this.ExecuteNonQueryOperationCompleted == null))
            {
                this.ExecuteNonQueryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExecuteNonQueryOperationCompleted);
            }
            this.InvokeAsync("ExecuteNonQuery", new object[] {
                    Query,
                    ConnName}, this.ExecuteNonQueryOperationCompleted, userState);
        }

        private void OnExecuteNonQueryOperationCompleted(object arg)
        {
            if ((this.ExecuteNonQueryCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ExecuteNonQueryCompleted(this, new ExecuteNonQueryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("UsuarioValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ExecuteEscalar", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public WebApiResponse ExecuteEscalar(string Query, string ConnName)
        {
            object[] results = this.Invoke("ExecuteEscalar", new object[] {
                    Query,
                    ConnName});
            return ((WebApiResponse)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginExecuteEscalar(string Query, string ConnName, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("ExecuteEscalar", new object[] {
                    Query,
                    ConnName}, callback, asyncState);
        }

        /// <remarks/>
        public WebApiResponse EndExecuteEscalar(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((WebApiResponse)(results[0]));
        }

        /// <remarks/>
        public void ExecuteEscalarAsync(string Query, string ConnName)
        {
            this.ExecuteEscalarAsync(Query, ConnName, null);
        }

        /// <remarks/>
        public void ExecuteEscalarAsync(string Query, string ConnName, object userState)
        {
            if ((this.ExecuteEscalarOperationCompleted == null))
            {
                this.ExecuteEscalarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExecuteEscalarOperationCompleted);
            }
            this.InvokeAsync("ExecuteEscalar", new object[] {
                    Query,
                    ConnName}, this.ExecuteEscalarOperationCompleted, userState);
        }

        private void OnExecuteEscalarOperationCompleted(object arg)
        {
            if ((this.ExecuteEscalarCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ExecuteEscalarCompleted(this, new ExecuteEscalarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("UsuarioValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TestConnection", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public WebApiResponse TestConnection(string ConnName)
        {
            object[] results = this.Invoke("TestConnection", new object[] {
                    ConnName});
            return ((WebApiResponse)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginTestConnection(string ConnName, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("TestConnection", new object[] {
                    ConnName}, callback, asyncState);
        }

        /// <remarks/>
        public WebApiResponse EndTestConnection(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((WebApiResponse)(results[0]));
        }

        /// <remarks/>
        public void TestConnectionAsync(string ConnName)
        {
            this.TestConnectionAsync(ConnName, null);
        }

        /// <remarks/>
        public void TestConnectionAsync(string ConnName, object userState)
        {
            if ((this.TestConnectionOperationCompleted == null))
            {
                this.TestConnectionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTestConnectionOperationCompleted);
            }
            this.InvokeAsync("TestConnection", new object[] {
                    ConnName}, this.TestConnectionOperationCompleted, userState);
        }

        private void OnTestConnectionOperationCompleted(object arg)
        {
            if ((this.TestConnectionCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TestConnectionCompleted(this, new TestConnectionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://tempuri.org/", IsNullable = false)]
    public partial class WebApiUser : System.Web.Services.Protocols.SoapHeader
    {

        private string userNameField;

        private string passwordField;

        private System.Xml.XmlAttribute[] anyAttrField;

        /// <remarks/>
        public string UserName
        {
            get
            {
                return this.userNameField;
            }
            set
            {
                this.userNameField = value;
            }
        }

        /// <remarks/>
        public string Password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get
            {
                return this.anyAttrField;
            }
            set
            {
                this.anyAttrField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/")]
    public partial class WebApiResponse
    {

        private HttpStatusCode estatusCodeField;

        private string messageField;

        private object dataField;

        private DataTable dataTableField;

        /// <remarks/>
        public HttpStatusCode EstatusCode
        {
            get
            {
                return this.estatusCodeField;
            }
            set
            {
                this.estatusCodeField = value;
            }
        }

        /// <remarks/>
        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }

        /// <remarks/>
        public object Data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
        /// <remarks/>
        public DataTable DataTable
        {
            get
            {
                return this.dataTableField;
            }
            set
            {
                this.dataTableField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/")]
    public enum HttpStatusCode
    {

        /// <remarks/>
        Continue,

        /// <remarks/>
        SwitchingProtocols,

        /// <remarks/>
        OK,

        /// <remarks/>
        Created,

        /// <remarks/>
        Accepted,

        /// <remarks/>
        NonAuthoritativeInformation,

        /// <remarks/>
        NoContent,

        /// <remarks/>
        ResetContent,

        /// <remarks/>
        PartialContent,

        /// <remarks/>
        MultipleChoices,

        /// <remarks/>
        Ambiguous,

        /// <remarks/>
        MovedPermanently,

        /// <remarks/>
        Moved,

        /// <remarks/>
        Found,

        /// <remarks/>
        Redirect,

        /// <remarks/>
        SeeOther,

        /// <remarks/>
        RedirectMethod,

        /// <remarks/>
        NotModified,

        /// <remarks/>
        UseProxy,

        /// <remarks/>
        Unused,

        /// <remarks/>
        TemporaryRedirect,

        /// <remarks/>
        RedirectKeepVerb,

        /// <remarks/>
        BadRequest,

        /// <remarks/>
        Unauthorized,

        /// <remarks/>
        PaymentRequired,

        /// <remarks/>
        Forbidden,

        /// <remarks/>
        NotFound,

        /// <remarks/>
        MethodNotAllowed,

        /// <remarks/>
        NotAcceptable,

        /// <remarks/>
        ProxyAuthenticationRequired,

        /// <remarks/>
        RequestTimeout,

        /// <remarks/>
        Conflict,

        /// <remarks/>
        Gone,

        /// <remarks/>
        LengthRequired,

        /// <remarks/>
        PreconditionFailed,

        /// <remarks/>
        RequestEntityTooLarge,

        /// <remarks/>
        RequestUriTooLong,

        /// <remarks/>
        UnsupportedMediaType,

        /// <remarks/>
        RequestedRangeNotSatisfiable,

        /// <remarks/>
        ExpectationFailed,

        /// <remarks/>
        UpgradeRequired,

        /// <remarks/>
        InternalServerError,

        /// <remarks/>
        NotImplemented,

        /// <remarks/>
        BadGateway,

        /// <remarks/>
        ServiceUnavailable,

        /// <remarks/>
        GatewayTimeout,

        /// <remarks/>
        HttpVersionNotSupported,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    public delegate void ExecuteQueryCompletedEventHandler(object sender, ExecuteQueryCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ExecuteQueryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal ExecuteQueryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public WebApiResponse Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((WebApiResponse)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    public delegate void ExecuteNonQueryCompletedEventHandler(object sender, ExecuteNonQueryCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ExecuteNonQueryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal ExecuteNonQueryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public WebApiResponse Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((WebApiResponse)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    public delegate void ExecuteEscalarCompletedEventHandler(object sender, ExecuteEscalarCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ExecuteEscalarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal ExecuteEscalarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public WebApiResponse Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((WebApiResponse)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    public delegate void TestConnectionCompletedEventHandler(object sender, TestConnectionCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TestConnectionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal TestConnectionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public WebApiResponse Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((WebApiResponse)(this.results[0]));
            }
        }
    }
}

