//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace Mane.CFDI.v4
{
    public interface IComprobante
    {
        ComprobanteAddenda Addenda { get; set; }
        string Certificado { get; set; }
        ComprobanteCfdiRelacionados[] CfdiRelacionados { get; set; }
        ComprobanteComplemento Complemento { get; set; }
        ComprobanteConcepto[] Conceptos { get; set; }
        string CondicionesDePago { get; set; }
        string Confirmacion { get; set; }
        decimal Descuento { get; set; }
        bool DescuentoSpecified { get; set; }
        ComprobanteEmisor Emisor { get; set; }
        string Exportacion { get; set; }
        DateTime Fecha { get; set; }
        string Folio { get; set; }
        string FormaPago { get; set; }
        ComprobanteImpuestos Impuestos { get; set; }
        ComprobanteInformacionGlobal InformacionGlobal { get; set; }
        string LugarExpedicion { get; set; }
        string MetodoPago { get; set; }
        string Moneda { get; set; }
        string NoCertificado { get; set; }
        ComprobanteReceptor Receptor { get; set; }
        string Sello { get; set; }
        string Serie { get; set; }
        decimal SubTotal { get; set; }
        decimal TipoCambio { get; set; }
        bool TipoCambioSpecified { get; set; }
        string TipoDeComprobante { get; set; }
        decimal Total { get; set; }
        string Version { get; set; }
    }
}