//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mane.CFDI.Interfaces
{
    public interface IComprobanteConceptoACuentaTerceros
    {
        string DomicilioFiscalACuentaTerceros { get; set; }
        string NombreACuentaTerceros { get; set; }
        string RegimenFiscalACuentaTerceros { get; set; }
        string RfcACuentaTerceros { get; set; }
    }
}