//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace Mane.CFDI.Interfaces
{
    public interface IComprobanteConceptoParte
    {
        decimal Cantidad { get; set; }
        string ClaveProdServ { get; set; }
        string Descripcion { get; set; }
        decimal Importe { get; set; }
        bool ImporteSpecified { get; set; }
        List<IComprobanteConceptoParteInformacionAduanera> InformacionAduanera { get; set; }
        string NoIdentificacion { get; set; }
        string Unidad { get; set; }
        decimal ValorUnitario { get; set; }
        bool ValorUnitarioSpecified { get; set; }
    }
}