//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mane.CFDI.Interfaces
{
    public interface IComprobanteConceptoImpuestosTraslado
    {
        decimal Base { get; set; }
        decimal Importe { get; set; }
        bool ImporteSpecified { get; set; }
        string Impuesto { get; set; }
        decimal TasaOCuota { get; set; }
        bool TasaOCuotaSpecified { get; set; }
        string TipoFactor { get; set; }
    }
}