//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mane.CFDI.Interfaces
{
    public interface IPagoDoctoRelacionado
    {
        decimal EquivalenciaDR { get; set; }
        bool EquivalenciaDRSpecified { get; set; }
        string Folio { get; set; }
        string IdDocumento { get; set; }
        decimal ImpPagado { get; set; }
        decimal ImpSaldoAnt { get; set; }
        decimal ImpSaldoInsoluto { get; set; }
        IPagoDoctoRelacionadoImpuestosDR ImpuestosDR { get; set; }
        string MonedaDR { get; set; }
        string NumParcialidad { get; set; }
        string ObjetoImpDR { get; set; }
        string Serie { get; set; }
    }
}