//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mane.CFDI.Interfaces
{
    public interface IPagoImpuestosPTrasladoP
    {
        decimal BaseP { get; set; }
        decimal ImporteP { get; set; }
        bool ImportePSpecified { get; set; }
        string ImpuestoP { get; set; }
        decimal TasaOCuotaP { get; set; }
        bool TasaOCuotaPSpecified { get; set; }
        string TipoFactorP { get; set; }
    }
}