//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mane.CFDI.Interfaces
{
    public interface IPagoDoctoRelacionadoImpuestosDRRetencionDR
    {
        decimal BaseDR { get; set; }
        decimal ImporteDR { get; set; }
        string ImpuestoDR { get; set; }
        decimal TasaOCuotaDR { get; set; }
        string TipoFactorDR { get; set; }
    }
}