//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Mane.CFDI.Interfaces
{
    public interface IPago
    {
        string CadPago { get; set; }
        byte[] CertPago { get; set; }
        string CtaBeneficiario { get; set; }
        string CtaOrdenante { get; set; }
        List<IPagoDoctoRelacionado> DoctoRelacionado { get; set; }
        DateTime FechaPago { get; set; }
        string FormaDePagoP { get; set; }
        IPagoImpuestosP ImpuestosP { get; set; }
        string MonedaP { get; set; }
        decimal Monto { get; set; }
        string NomBancoOrdExt { get; set; }
        string NumOperacion { get; set; }
        string RfcEmisorCtaBen { get; set; }
        string RfcEmisorCtaOrd { get; set; }
        byte[] SelloPago { get; set; }
        string TipoCadPago { get; set; }
        bool TipoCadPagoSpecified { get; set; }
        decimal TipoCambioP { get; set; }
        bool TipoCambioPSpecified { get; set; }
    }
}