//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mane.CFDI.Interfaces
{
    public interface IPagosTotales
    {
        decimal MontoTotalPagos { get; set; }
        decimal TotalRetencionesIEPS { get; set; }
        bool TotalRetencionesIEPSSpecified { get; set; }
        decimal TotalRetencionesISR { get; set; }
        bool TotalRetencionesISRSpecified { get; set; }
        decimal TotalRetencionesIVA { get; set; }
        bool TotalRetencionesIVASpecified { get; set; }
        decimal TotalTrasladosBaseIVA0 { get; set; }
        bool TotalTrasladosBaseIVA0Specified { get; set; }
        decimal TotalTrasladosBaseIVA16 { get; set; }
        bool TotalTrasladosBaseIVA16Specified { get; set; }
        decimal TotalTrasladosBaseIVA8 { get; set; }
        bool TotalTrasladosBaseIVA8Specified { get; set; }
        decimal TotalTrasladosBaseIVAExento { get; set; }
        bool TotalTrasladosBaseIVAExentoSpecified { get; set; }
        decimal TotalTrasladosImpuestoIVA0 { get; set; }
        bool TotalTrasladosImpuestoIVA0Specified { get; set; }
        decimal TotalTrasladosImpuestoIVA16 { get; set; }
        bool TotalTrasladosImpuestoIVA16Specified { get; set; }
        decimal TotalTrasladosImpuestoIVA8 { get; set; }
        bool TotalTrasladosImpuestoIVA8Specified { get; set; }
    }
}