//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mane.CFDI.Interfaces
{
    public interface IReceptor
    {
        string DomicilioFiscalReceptor { get; set; }
        string Nombre { get; set; }
        string NumRegIdTrib { get; set; }
        string RegimenFiscalReceptor { get; set; }
        string ResidenciaFiscal { get; set; }
        string Rfc { get; set; }
        string UsoCFDI { get; set; }
    }
}